//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CSubset.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CSubsetParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICSubsetListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CSubsetParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CSubsetParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CSubsetParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CSubsetParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclaration([NotNull] CSubsetParser.VarDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.varDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclaration([NotNull] CSubsetParser.VarDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.varDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDeclarator([NotNull] CSubsetParser.VarDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.varDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDeclarator([NotNull] CSubsetParser.VarDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] CSubsetParser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] CSubsetParser.TypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] CSubsetParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] CSubsetParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.controlStructure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlStructure([NotNull] CSubsetParser.ControlStructureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.controlStructure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlStructure([NotNull] CSubsetParser.ControlStructureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] CSubsetParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] CSubsetParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] CSubsetParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] CSubsetParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] CSubsetParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] CSubsetParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhileStatement([NotNull] CSubsetParser.DoWhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhileStatement([NotNull] CSubsetParser.DoWhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatement([NotNull] CSubsetParser.SwitchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatement([NotNull] CSubsetParser.SwitchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.caseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseBlock([NotNull] CSubsetParser.CaseBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.caseBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseBlock([NotNull] CSubsetParser.CaseBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaration([NotNull] CSubsetParser.FunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaration([NotNull] CSubsetParser.FunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] CSubsetParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] CSubsetParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.ioFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIoFunction([NotNull] CSubsetParser.IoFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.ioFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIoFunction([NotNull] CSubsetParser.IoFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.pointerManipulation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerManipulation([NotNull] CSubsetParser.PointerManipulationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.pointerManipulation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerManipulation([NotNull] CSubsetParser.PointerManipulationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclaration([NotNull] CSubsetParser.StructDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclaration([NotNull] CSubsetParser.StructDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.unionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnionDeclaration([NotNull] CSubsetParser.UnionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.unionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnionDeclaration([NotNull] CSubsetParser.UnionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSubsetParser.preprocessorDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreprocessorDirective([NotNull] CSubsetParser.PreprocessorDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSubsetParser.preprocessorDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreprocessorDirective([NotNull] CSubsetParser.PreprocessorDirectiveContext context);
}
